-- ==============================================================================
-- 1. PROFILES TABLE & TRIGGERS
-- ==============================================================================

-- Create profiles table if it does not exist
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  full_name TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create policy for users to view their own profile if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'profiles' AND policyname = 'Users can view own profile'
  ) THEN
    CREATE POLICY "Users can view own profile" ON public.profiles
      FOR SELECT TO authenticated
      USING (auth.uid() = id);
  END IF;
END $$;

-- Create policy for users to update their own profile if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'profiles' AND policyname = 'Users can update own profile'
  ) THEN
    CREATE POLICY "Users can update own profile" ON public.profiles
      FOR UPDATE TO authenticated
      USING (auth.uid() = id)
      WITH CHECK (auth.uid() = id);
  END IF;
END $$;

-- Function to handle new user insertion automatically
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, is_admin)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', SPLIT_PART(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'full_name',
    FALSE
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute on user creation if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'on_auth_user_created'
  ) THEN
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
  END IF;
END $$;

-- Prevent is_admin from being changed via profile inserts or updates unless by service_role
CREATE OR REPLACE FUNCTION public.prevent_is_admin_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_setting('role', true) <> 'service_role'
     AND NEW.is_admin IS DISTINCT FROM COALESCE(OLD.is_admin, false) THEN
    RAISE EXCEPTION 'Changing is_admin is not allowed.';
  END IF;

  RETURN NEW;
END;
$$;

DO $$
BEGIN
  -- Drop existing trigger if it exists so we can recreate for BEFORE INSERT OR UPDATE
  DROP TRIGGER IF EXISTS prevent_is_admin_change_trigger ON public.profiles;

  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'prevent_is_admin_change_trigger'
  ) THEN
    CREATE TRIGGER prevent_is_admin_change_trigger
      BEFORE INSERT OR UPDATE ON public.profiles
      FOR EACH ROW
      EXECUTE FUNCTION public.prevent_is_admin_change();
  END IF;
END $$;

-- ==============================================================================
-- 2. POSTS TABLE & POLICIES
-- ==============================================================================

-- Create posts table if it does not exist
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on posts
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read posts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'posts' AND policyname = 'Anyone can read posts'
  ) THEN
    CREATE POLICY "Anyone can read posts" ON public.posts
      FOR SELECT USING (true);
  END IF;
END $$;

-- Policy: Authenticated users can insert their own posts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'posts' AND policyname = 'Users can create posts'
  ) THEN
    CREATE POLICY "Users can create posts" ON public.posts
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- Policy: Users can update their own posts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'posts' AND policyname = 'Users can update own posts'
  ) THEN
    CREATE POLICY "Users can update own posts" ON public.posts
      FOR UPDATE USING (auth.uid() = user_id);
  END IF;
END $$;

-- Policy: Users can delete their own posts
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'posts' AND policyname = 'Users can delete own posts'
  ) THEN
    CREATE POLICY "Users can delete own posts" ON public.posts
      FOR DELETE TO authenticated
      USING (auth.uid() = user_id);
  END IF;
END $$;

-- Policy: Admins can delete any post
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'posts' AND policyname = 'Admin delete any post'
  ) THEN
    CREATE POLICY "Admin delete any post" ON public.posts
      FOR DELETE TO authenticated
      USING (
        EXISTS (
          SELECT 1
          FROM public.profiles
          WHERE public.profiles.id = auth.uid()
            AND public.profiles.is_admin = true
        )
      );
  END IF;
END $$;

-- Policy: Restrictive policy requiring MFA (aal2) for posts operations IF MFA is enabled for the user
DO $$
BEGIN
  -- Drop old policy if exists so it can be updated
  DROP POLICY IF EXISTS "Require MFA for posts" ON public.posts;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'posts' AND policyname = 'Require MFA for posts if enabled'
  ) THEN
    CREATE POLICY "Require MFA for posts if enabled" ON public.posts
      AS RESTRICTIVE
      FOR ALL
      TO authenticated
      USING (
        (SELECT (auth.jwt()->>'aal')) = 'aal2'
        OR NOT EXISTS (
          SELECT 1 FROM auth.mfa_factors
          WHERE auth.mfa_factors.user_id = auth.uid()
            AND auth.mfa_factors.status = 'verified'
        )
      );
  END IF;
END $$;
